### ISSUE TITLE
Brak klamry

### ISSUE THREAD

**Issue by krzysztofwodecki** [Abbion/Ankiette#15]
Tutaj nam brakuje klamerki, wywala błąd, nie zapomnieć naprawić przy następnej okazji.

**Comment by karolke99** [comment]
tutaj czyli ?

**Comment by krzysztofwodecki** [comment]
Proszę się nie śmiać, zaznaczyłem w kodzie to nie moja wina, że github nie ogarnął 😭😭😭 Nawet jeśli to i tak już dodałem ją w ostatnim moim commicie.
