### ISSUE TITLE
Problem z przetestowaniem backendu

### ISSUE THREAD

**Issue by sweakpl** [Abbion/Ankiette#18]
@krzysztofwodecki, @karolke99, @antek3737, chciałem zobaczyć na nasz backend i natrafiłem na 2 problemy:

1. Tutaj jest mały problem - funkcja `getEnabled()` nie jest domknięta i przez to nasze API nie działa. To był błąd w mergu (https://github.com/Abbion/Ankiette/pull/7):

https://github.com/Abbion/Ankiette/blob/ea7ff22ada44f5fe149adca5de7eef9e8ac03789/api/src/repository/UserRepository.php#L79-L88

##### Edit:
Dobra, widzę, że już był Issue na ten temat, i @krzysztofwodecki dodał już u siebie commita naprawiającego.

2. Jeśli poprawię ten błąd, to później brakuje pliku (który jest w `.gitignore`) - `emailConfig.php`:

```
Warning: require_once(emailConfig.php): failed to open stream: No such file or directory in /app/email/EmailServer.php on line 10

Fatal error: require_once(): Failed opening required 'emailConfig.php' (include_path='.:/usr/local/lib/php') in /app/email/EmailServer.php on line 10
```

Nie znalazłem też miejsca, z którego można go sobie pobrać albo jak go stworzyć.

**Comment by krzysztofwodecki** [comment]
Ten plik emailConfig.php jest opisany na general na Discordzie 6 kwietnia.

**Comment by sweakpl** [comment]
Aha, dobra, to mnie discord zmylił:

![obraz](https://user-images.githubusercontent.com/70141120/165337547-2d5bc582-d7a3-4269-b27b-a1e5927d290a.png)

Myślałem też, że to będzie na `#backend`.
